SEED_DATA = {
    "铭瑄B760M主板箱子": [
        {"name": "硬盘", "tags": "电脑,存储"},
        {"name": "CPU", "tags": "电脑,处理器"},
        {"name": "PCIe类扩展", "tags": "电脑,扩展卡"},
        {"name": "亮机卡", "tags": "电脑,显卡"},
        {"name": "鼠标增重块", "tags": "鼠标,配件"},
        {"name": "机箱挡板", "tags": "电脑,机箱"},
        {"name": "便宜鼠标", "quantity": 2, "tags": "鼠标"},
        {"name": "笔记本增高架", "tags": "笔记本,支架"},
        {"name": "机箱滤网（高密度）", "tags": "电脑,机箱,防尘"},
        {"name": "耳机", "quantity": 3, "tags": "音频"},
        {"name": "HDMI欺骗器", "condition": "损坏", "tags": "HDMI,显示,欺骗器"},
        {"name": "真我 GT Neo5 SE 手机膜和辅助器材", "tags": "手机,真我,GT Neo5 SE"},
    ],
    "漫步者820NB盒子": [
        {"name": "羽毛球胶", "tags": "运动"},
        {"name": "魔方", "tags": "玩具"},
        {"name": "笔芯", "tags": "文具"},
        {"name": "手套", "tags": "日用品"},
        {"name": "玩具等", "tags": "玩具", "notes": "盒内还有其他零散玩具"},
    ],
    "秒界按摩椅盒子": [
        {"name": "麦克风简易支架", "tags": "麦克风,支架"},
        {"name": "订书器", "tags": "文具"},
        {"name": "打气筒", "tags": "工具"},
        {"name": "防手汗沙袋", "tags": "运动,防手汗"},
    ],
    "南小萌甜瓜盒子": [
        {"name": "网线钳", "tags": "网络,工具"},
        {"name": "网线仪", "tags": "网络,测试"},
        {"name": "网口", "tags": "网络,RJ45"},
    ],
    "全家高钙营养奶粉箱子": [
        {"name": "粘钩", "tags": "日用品,收纳"},
    ],
    "银色箱子": [
        {"name": "测电笔（手动导电）", "tags": "电工,工具"},
        {"name": "测电笔（充电）", "condition": "精度不高/廉价", "tags": "电工,工具"},
        {"name": "插排", "tags": "电源"},
        {"name": "DC口大圆口变小圆口", "tags": "DC,转接,电源"},
        {"name": "鼠标垫", "quantity": 2, "tags": "鼠标,配件"},
    ],
    "蓝色箱子": [
        {"name": "12V 3A 电源适配器", "tags": "电源,适配器,12V"},
        {"name": "12V 2A 电源适配器", "tags": "电源,适配器,12V"},
        {"name": "12V 6A 电源适配器", "tags": "电源,适配器,12V"},
        {"name": "耳机支架", "tags": "耳机,支架"},
    ],
    "果冻橙箱子": [
        {"name": "黑色螺丝刀", "tags": "工具,螺丝刀"},
        {"name": "各种螺丝和基础螺丝刀", "quantity_text": "多种", "tags": "工具,螺丝,螺丝刀"},
    ],
    "透明箱子1": [
        {"name": "报销车票凭证", "tags": "票据,凭证"},
        {"name": "电池", "quantity_text": "一些", "condition": "没电", "tags": "电池"},
        {"name": "扣子", "quantity_text": "一些", "notes": "用来缝补衣物", "tags": "衣物,缝补"},
        {"name": "小夹子", "quantity_text": "一些", "tags": "日用品"},
        {"name": "订书钉", "quantity_text": "一些", "tags": "文具"},
    ],
    "透明箱子2": [
        {"name": "橡皮", "tags": "文具"},
        {"name": "视频接口防尘塞", "tags": "电脑,防尘塞,视频接口"},
        {"name": "随身WiFi（4G）", "tags": "网络,4G,WiFi"},
        {"name": "移动硬盘盒", "tags": "存储,硬盘盒"},
        {"name": "显卡欺骗器", "tags": "显卡,显示,欺骗器"},
        {"name": "红外线扫描仪", "tags": "红外,扫描仪"},
        {"name": "SD卡和SD卡读取器", "tags": "SD卡,读卡器,存储"},
        {"name": "温度传感器", "notes": "从保温杯拆下来的", "tags": "传感器,温度"},
        {"name": "华为手环", "notes": "带充电器", "tags": "华为,手环,穿戴"},
        {"name": "小黄刀", "notes": "拨线用", "tags": "工具,拨线"},
        {"name": "镊子", "tags": "工具"},
        {"name": "白边填充液", "tags": "手机膜,维修"},
        {"name": "平衡仪（水平仪）", "condition": "绿色", "tags": "工具,水平仪"},
        {"name": "小刀", "notes": "比较锋利，用于削铅笔", "tags": "工具,小刀"},
        {"name": "电脑清灰工具套装", "notes": "含小方片、翘板、固态硬盘散热贴纸、按压硅脂用指套、硅脂、酒精片", "tags": "电脑,清灰,维修,硅脂"},
    ],
    "透明超大鱼缸箱子": [
        {"name": "USB-C线材", "quantity_text": "非常多", "notes": "长线在箱子周围挂着，短线在盒子的盒子里面", "tags": "USB-C,Type-C,线材"},
        {"name": "USB-A线材", "quantity_text": "比较多", "notes": "长线在箱子周围挂着，短线在盒子的盒子里面", "tags": "USB-A,线材"},
        {"name": "USB-C扩展坞（USB-C + USB-A + HDMI）", "notes": "USB-C 输入；扩展为 USB-C、USB-A、HDMI 接口", "tags": "扩展坞,USB-C,USB-A,HDMI"},
        {"name": "USB-C扩展坞（3×USB-A + HDMI，无PD）", "notes": "USB-C 输入；3 个 USB-A、1 个 HDMI；无 PD 供电", "tags": "扩展坞,USB-C,USB-A,HDMI,无PD"},
        {"name": "USB-C扩展坞（USB-A 3.0 + 2×USB-A 2.0 + PD + HDMI）", "notes": "USB-C 输入；1 个 USB-A 3.0、2 个 USB-A 2.0、1 个 PD 供电口、1 个 HDMI", "tags": "扩展坞,USB-C,USB-A,USB3.0,USB2.0,PD,HDMI"},
        {"name": "USB-A扩展坞（网卡口）", "notes": "USB-A 输入；扩展为 1 个网卡口", "tags": "扩展坞,USB-A,网卡,以太网,RJ45"},
        {"name": "USB-A扩展坞（百兆网卡口）", "notes": "USB-A 输入；扩展为 1 个百兆网卡口", "tags": "扩展坞,USB-A,网卡,百兆,100Mbps,以太网,RJ45"},
        {"name": "USB-C转3.5mm音频转换器", "tags": "转换器,USB-C,Type-C,3.5mm,音频"},
        {"name": "USB-B转USB-A转换器", "tags": "转换器,USB-B,USB-A"},
        {"name": "USB-A ↔ USB Micro-B 硬盘线", "notes": "Micro-B 硬盘专用接口", "tags": "USB-A,Micro-B,USB Micro-B,硬盘,线材"},
        {"name": "USB-A ↔ USB Mini-B 线（白色）", "quantity": 2, "notes": "游戏手柄、麦克风等 Mini-B 接口设备使用；白色", "tags": "USB-A,Mini-B,USB Mini-B,游戏手柄,麦克风,线材,白色"},
        {"name": "USB-A ↔ USB Mini-B 线（黑色低速率）", "notes": "游戏手柄、麦克风等 Mini-B 接口设备使用；黑色，低速率", "tags": "USB-A,Mini-B,USB Mini-B,游戏手柄,麦克风,线材,黑色,低速率"},
    ],
    "纯甄酸奶箱子": [
        {"name": "超长HDMI线材", "tags": "HDMI,线材"},
        {"name": "1米HDMI线材", "tags": "HDMI,线材"},
        {"name": "HDMI转VGA + 音频输出 + USB 转接器", "tags": "HDMI,VGA,转接器,USB"},
        {"name": "HDMI延长线", "tags": "HDMI,延长线"},
        {"name": "VGA线", "tags": "VGA,线材"},
        {"name": "VGA视频采集卡", "notes": "可输出为 HDMI 或 USB；通过 USB 时可用 OBS 或手机软件获取视频", "tags": "VGA,视频采集卡,采集卡,HDMI,USB,OBS,手机"},
    ],
    "常用盒子【黑色透明】": [],
    "常用盒子【白色透明】": [
        {"name": "纸", "tags": "常用,文具,纸张"},
        {"name": "笔", "tags": "常用,文具"},
        {"name": "便携标签", "tags": "常用,标签,收纳,文具"},
        {"name": "粘小飞虫板子", "tags": "常用,日用品,粘虫板"},
    ],
}

CONTAINER_NOTES = {
    "常用盒子【黑色透明】": "经常打开的盒子，内部物品不做统计。",
    "常用盒子【白色透明】": "常用物品盒。",
}
